/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : IDL.Nat,
  'joinDate' : Time,
});
export const Transaction = IDL.Record({
  'user' : IDL.Principal,
  'taskId' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTask' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'registerUser' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Nat,
    'joinDate' : Time,
  });
  const Transaction = IDL.Record({
    'user' : IDL.Principal,
    'taskId' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTask' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'registerUser' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };